# --------------------------------------------------------------------------
# Partie public
# --------------------------------------------------------------------------
nagios_JID_jobs:
    pattern:  /jobs
    defaults: { _controller: AriiJIDBundle:Nagios:jobs }
